use <../scad/core/grid.scad>

parent_size = [56.7, 65];

grid_plist(["type","grid",
            "size", parent_size,
            "rows", [["h", 12.0, "cells",
                      [["w", 0.25],
                       ["w", 0.25, "grid",
                        ["type","grid",
                         "rows",
                         [["h", 0.5, "cells",
                           [["w", 1.0]]],
                          ["h", 0.5, "cells",
                           [["w", 0.5,
                             "slot", ["type",
                                      "rect",
                                      "size", [10, 5]],
                             "placeholder", ["type",
                                             "atm_fuse_holder"]],
                            ["w", 0.5]]]]]],
                       ["w", 0.25],
                       ["w", 0.25]]],

                     ["h", 11.0, "cells",
                      [["w", 0.25],
                       ["w", 0.5],
                       ["w", 0.25]]],
                     ["h", 6.0,  "cells", [["w", 0.25],
                                           ["w", 0.5],
                                           ["w", 0.25]]],
                     ["h", 11.0, "cells", [["w", 0.5],
                                           ["w", 0.5]]],
                     ["h", 3.0,  "cells", [["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2]]],
                     ["h", 3.0,  "cells", [["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2],
                                           ["w", 0.2]]],
                     ["h", 4.0,  "cells", [["w", 0.1],
                                           ["w", 0.8],
                                           ["w", 0.1]]]]],
           debug=true);